FROM nginx:1.27-alpine

COPY index.html /usr/share/nginx/html/index.html
COPY logo.svg /usr/share/nginx/html/logo.svg
COPY favicon.svg /usr/share/nginx/html/favicon.svg
COPY screenshots /usr/share/nginx/html/screenshots

EXPOSE 80